######################################################################
#
# File name : module_compile.do
# Created on: Wed May 15 16:40:48 CEST 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom -64 -93 -work xil_defaultlib  \
"../../../../sevenseg7.srcs/sources_1/imports/hdl/sevenseg.vhd" \
"../../../../sevenseg7.srcs/sources_1/imports/hdl/module.vhd" \


